import AppKit
import Combine

/// Опрос системного буфера каждые 0,5 секунды (подход Maccy):
/// следим за changeCount и забираем новые текстовые записи.
///
/// Пропускаем:
/// - confidential/transient/auto-generated типы (стандарт nspasteboard.org);
/// - менеджеры паролей из статического списка исключений;
/// - тексты длиннее ClipboardStore.maxItemCharacters;
/// - пустые и пробельные строки.
///
/// Наши собственные копирования в буфер (кнопки истории) тоже попадают
/// в changeCount — хранилище дедуплицирует их перемещением наверх.
@MainActor
final class PasteboardMonitor: ObservableObject {

    /// Хранение настройки «Собирать историю буфера» (по умолчанию включено).
    static let storageKey = "ClipboardHistoryEnabled"

    static var historyEnabledByDefault: Bool {
        (UserDefaults.standard.object(forKey: storageKey) as? Bool) ?? true
    }

    /// История не пишется из менеджеров паролей (общий список политики).
    static let excludedBundleIDs: Set<String> = ExcludedApps.passwordManagers

    private static let excludedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType",
    ]

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private let store: ClipboardStore

    init(store: ClipboardStore) {
        self.store = store
    }

    var isRunning: Bool { timer != nil }

    func start() {
        guard timer == nil else { return }
        lastChangeCount = NSPasteboard.general.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.poll()
            }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let types = Set(
            (pasteboard.pasteboardItems ?? []).flatMap(\.types).map(\.rawValue)
        )
        guard !types.isEmpty else { return }
        if types.contains(where: { Self.excludedTypes.contains($0) }) { return }

        let frontmost = NSWorkspace.shared.frontmostApplication
        if let bundleID = frontmost?.bundleIdentifier,
           Self.excludedBundleIDs.contains(bundleID) { return }

        guard let text = pasteboard.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
              text.count <= ClipboardStore.maxItemCharacters else { return }

        store.add(
            text: text,
            sourceAppBundleID: frontmost?.bundleIdentifier,
            sourceAppName: frontmost?.localizedName
        )
    }
}
