import AppKit
import Combine

/// Опрос системного буфера каждые 0,5 секунды (подход Maccy):
/// следим за changeCount и забираем новые текстовые записи.
///
/// Пропускаем:
/// - confidential/transient/auto-generated типы (стандарт nspasteboard.org);
/// - менеджеры паролей из статического списка исключений;
/// - тексты длиннее ClipboardStore.maxItemCharacters;
/// - пустые и пробельные строки.
///
/// Наши собственные копирования (кнопки истории, транскрипт диктовки)
/// опрос пропускает по ignoredChangeCount: подъём карточки делает touch,
/// персист транскрипта — сама диктовка, с правильной атрибуцией.
@MainActor
final class PasteboardMonitor: ObservableObject {

    /// Хранение настройки «Собирать историю буфера» (по умолчанию включено).
    static let storageKey = "ClipboardHistoryEnabled"

    static var historyEnabledByDefault: Bool {
        (UserDefaults.standard.object(forKey: storageKey) as? Bool) ?? true
    }

    /// История не пишется из менеджеров паролей и приложений, исключённых
    /// пользователем (общая политика, спецификация §8.9).
    static var excludedBundleIDs: Set<String> {
        ExcludedApps.passwordManagers.union(ExcludedApps.userExcluded)
    }

    private static let excludedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType",
    ]

    /// Изменение буфера, сделанное самой Aza (диктовка кладёт транскрипт,
    /// копирование карточки из истории — её содержимое): опрос его
    /// пропускает. Иначе транскрипт получал бы атрибуцию фронтмоста
    /// вместо «Aza (диктовка)», копия из истории затирала бы
    /// происхождение карточки (touch поднимает её сам), и каждая своя
    /// запись шифровалась бы на диск дважды.
    static var ignoredChangeCount = -1

    private var timer: Timer?
    private var captureGeneration = UUID()
    private var lastChangeCount = NSPasteboard.general.changeCount
    /// Все приложения, побывавшие активными с прошлого тика: копия
    /// случилась где-то между тиками, и источником могло быть ЛЮБОЕ из
    /// них — даже «заскочить в менеджер паролей и обратно» между двумя
    /// опросами не обходит исключения (ложный пропуск лучше утечки).
    /// Наполняется уведомлениями NSWorkspace, не сэмплами на тиках.
    private var activeSinceLastPoll: Set<String> = []
    private var activationObserver: (any NSObjectProtocol)?
    private let store: ClipboardStore

    init(store: ClipboardStore) {
        self.store = store
    }

    var isRunning: Bool { timer != nil }

    func start() {
        guard timer == nil else { return }
        lastChangeCount = NSPasteboard.general.changeCount
        if let current = NSWorkspace.shared.frontmostApplication?.bundleIdentifier {
            activeSinceLastPoll = [current]
        }
        activationObserver = NSWorkspace.shared.notificationCenter.addObserver(
            forName: NSWorkspace.didActivateApplicationNotification,
            object: nil, queue: .main
        ) { [weak self] notification in
            azaAssumeMainUnchecked {
                guard let self,
                      let app = notification.userInfo?[NSWorkspace.applicationUserInfoKey]
                        as? NSRunningApplication,
                      let bundleID = app.bundleIdentifier else { return }
                self.activeSinceLastPoll.insert(bundleID)
            }
        }
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            azaAssumeMainUnchecked {
                self?.poll()
            }
        }
    }

    func stop() {
        captureGeneration = UUID()
        timer?.invalidate()
        timer = nil
        if let activationObserver {
            NSWorkspace.shared.notificationCenter.removeObserver(activationObserver)
            self.activationObserver = nil
        }
    }

    func poll() {
        let pasteboard = NSPasteboard.general
        let frontmost = NSWorkspace.shared.frontmostApplication
        var candidates = activeSinceLastPoll
        if let current = frontmost?.bundleIdentifier { candidates.insert(current) }
        // Новый интервал начинается с текущего фронтмоста.
        activeSinceLastPoll = frontmost?.bundleIdentifier.map { [$0] } ?? []
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        if pasteboard.changeCount == Self.ignoredChangeCount { return }

        let types = Set(
            (pasteboard.pasteboardItems ?? []).flatMap(\.types).map(\.rawValue)
        )
        guard !types.isEmpty else { return }
        if types.contains(where: { Self.excludedTypes.contains($0) }) { return }

        // Кандидаты в источники — все активные с прошлого тика. Исключён
        // любой — запись пропускается; их больше одного — атрибуция
        // неизвестна (nil), а не догадка.
        if candidates.contains(where: { Self.excludedBundleIDs.contains($0) }) { return }
        let ambiguous = candidates.count > 1

        classify(pasteboard,
                 sourceAppBundleID: ambiguous ? nil : frontmost?.bundleIdentifier,
                 sourceAppName: ambiguous ? nil : frontmost?.localizedName)
    }

    /// Приоритет классификации (стиль Maccy): файлы → изображение →
    /// ссылка → RTF → текст. Копия файла-картинки из Finder остаётся
    /// файловой ссылкой; содержимое файлов не читается.
    func classify(_ pasteboard: NSPasteboard,
                          sourceAppBundleID: String?, sourceAppName: String?) {
        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            azaDebugLog("Aza: clip kind=files n=\(urls.count)")
            store.addFiles(paths: urls.map(\.path),
                           sourceAppBundleID: sourceAppBundleID,
                           sourceAppName: sourceAppName)
            return
        }

        if let image = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff),
           image.count <= ClipboardStore.maxObjectBytes {
            // Декодирование, нормализация к PNG и миниатюра — в фоне:
            // на таймере главного потока большое изображение подвешивало
            // бы UI и сам опрос. В main возвращаемся только для записи.
            let generation = captureGeneration
            // Время — момент КОПИИ: текст, скопированный позже картинки,
            // добавляется синхронно и не должен оказаться под ней в истории.
            let copiedAt = Date()
            Self.imageDecodeQueue.async {
                guard Self.imageIsSafeToDecode(image),
                      let rep = NSBitmapImageRep(data: image),
                      let png = rep.representation(using: .png, properties: [:]) else {
                    azaDebugLog("Aza: clip image decode failed bytes=\(image.count)")
                    return
                }
                let thumbnail = Self.thumbnailPNG(from: png)
                let label = "Изображение \(rep.pixelsWide)×\(rep.pixelsHigh)"
                DispatchQueue.main.async { [weak self] in
                    azaAssumeMainUnchecked {
                        guard let self, self.isRunning,
                              self.captureGeneration == generation else { return }
                        azaDebugLog("Aza: clip kind=image bytes=\(png.count) thumb=\(thumbnail?.count ?? 0)")
                        self.store.addImage(png: png, label: label, thumbnail: thumbnail,
                                       sourceAppBundleID: sourceAppBundleID,
                                       sourceAppName: sourceAppName,
                                       copiedAt: copiedAt)
                    }
                }
            }
            return
        }

        if let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL],
           let url = urls.first, !url.isFileURL, url.scheme != nil {
            azaDebugLog("Aza: clip kind=link")
            store.addLink(url,
                          sourceAppBundleID: sourceAppBundleID,
                          sourceAppName: sourceAppName)
            return
        }

        if let rtf = pasteboard.data(forType: .rtf),
           rtf.count <= ClipboardStore.maxObjectBytes {
            // Плоский текст: из pasteboard, иначе из самого RTF.
            let text = pasteboard.string(forType: .string)
                ?? NSAttributedString(rtf: rtf, documentAttributes: nil)?.string
                ?? ""
            azaDebugLog("Aza: clip kind=rtf bytes=\(rtf.count)")
            store.addRTF(text: text, rtf: rtf,
                         sourceAppBundleID: sourceAppBundleID,
                         sourceAppName: sourceAppName)
            return
        }

        guard let text = pasteboard.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
              text.count <= ClipboardStore.maxItemCharacters else {
            azaDebugLog("Aza: clip kind=unclassified types=\(pasteboard.types?.count ?? 0)")
            return
        }
        classifyText(text,
                     sourceAppBundleID: sourceAppBundleID,
                     sourceAppName: sourceAppName)
    }

    /// Последовательная очередь декодирования изображений: сохраняет
    /// порядок при быстрых подряд копированиях (гонка «старое поверх
    /// нового» невозможна: main тоже последовательный).
    static let imageDecodeQueue = DispatchQueue(label: "com.tmmt.Aza.image-decode")

    /// Размер сжатого PNG/TIFF не ограничивает память после распаковки.
    /// ponytail: до 100 МБ RGBA на кадр; большие изображения требуют
    /// отдельного декодера с уменьшением размера до загрузки в память.
    nonisolated static func imageIsSafeToDecode(_ data: Data) -> Bool {
        guard data.count <= ClipboardStore.maxObjectBytes,
              let source = CGImageSourceCreateWithData(data as CFData,
                  [kCGImageSourceShouldCache: false] as CFDictionary),
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
              let width = properties[kCGImagePropertyPixelWidth] as? Int,
              let height = properties[kCGImagePropertyPixelHeight] as? Int,
              width > 0, height > 0 else { return false }
        return width <= ClipboardStore.maxObjectBytes / 4 / height
    }

    /// PNG-миниатюра ≤512px по длинной стороне через ImageIO —
    /// потокобезопасно без графического контекста AppKit. 512, а не меньше:
    /// карточка острова рисует превью ~412px на Retina (206pt × 2).
    private nonisolated static func thumbnailPNG(from imageData: Data) -> Data? {
        let options: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceThumbnailMaxPixelSize: 512,
            kCGImageSourceCreateThumbnailWithTransform: true,
        ]
        guard let source = CGImageSourceCreateWithData(imageData as CFData, nil),
              let cgImage = CGImageSourceCreateThumbnailAtIndex(
                source, 0, options as CFDictionary) else { return nil }
        return NSBitmapImageRep(cgImage: cgImage)
            .representation(using: .png, properties: [:])
    }

    /// Текстовая ветка вынесена: выше остаётся только маршрутизация типов.
    private func classifyText(_ text: String,
                              sourceAppBundleID: String?, sourceAppName: String?) {
        // Скопированный текстом URL — карточка-ссылка: тип public.url
        // кладут только браузеры, а ссылки чаще копируют как текст.
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        if let url = URL(string: trimmed),
           let scheme = url.scheme, ["http", "https"].contains(scheme),
           url.host != nil, !trimmed.contains(where: \.isWhitespace) {
            azaDebugLog("Aza: clip kind=link (text)")
            store.addLink(url,
                          sourceAppBundleID: sourceAppBundleID,
                          sourceAppName: sourceAppName)
            return
        }
        azaDebugLog("Aza: clip kind=text len=\(text.count)")
        store.add(
            text: text,
            sourceAppBundleID: sourceAppBundleID,
            sourceAppName: sourceAppName
        )
    }
}
